import type { Metadata } from "next";
import "./globals.css";
import { HeroPattern } from "@/components/HeroPattern";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      <HeroPattern />
        {/* <Providers>{children}</Providers> */}
        {children}
      </body>
    </html>
  );
}
